spring.profiles.include: hello

# disable actuator security
security.basic.enabled: false
management.security.enabled: false

# to be exposed on '/info' endpoint
info:
  id: @project.groupId@:@project.artifactId@:@project.version@
  github-url: https://github.com/svaponi/spring-boot-template


